#!/bin/bash

if [ -z "$1"]; then
    echo "Usage: $0 <repo-url> <ide>"
    exit 1
fi

git clone "$1" || exit

if [ -z "$2"]; then
    code "$1" || exit
elif [ "$2" == "vim"]; then
    vim "$1" || exit
elif [ "$2" == "nvim"]; then
    nvim "$1" || exit
else
    echo "Usage: $0 <repo-url> <ide>"
    echo "List of IDE's currently available:"
    echo "VSCode, Vim, Neovim"

    echo "If you want vim or neovim, then do $0 <repo-url> vim and $0 <repo-url> nvim"
    echo "If you want VSCode don't put anything"
fi